version: "3.3"
services:

    bot:
        image: node:alpine
        working_dir: /home/node/app
        volumes: 
            - ./:/home/node/app
        restart: unless-stopped
        command: "npm run start-bot"

    web:
        image: node:alpine
        ports:
            - 8080:8080
        working_dir: /home/node/app
        volumes: 
            - ./:/home/node/app
        restart: unless-stopped
        command: "npm run start-web"

    mongo:
        image: mongo
        restart: unless-stopped
        volumes: 
            - db-data:/data/db
            - ./script/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: 1234
          MONGO_INITDB_DATABASE: quizz
    
    mongo-express:
        image: mongo-express
        restart: unless-stopped
        ports:
          - 8081:8081
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: 1234

volumes:
    db-data:
